Enable EKS managed nodegroups and EKS master node to worker node connectivity added
tothenew/terraform-aws-eks pull request #12
Opened 2023-06-06 12:18 UTC by guptavasu1

2023-07-04 10:29 UTC, prashantgupta123 requested changes
1. New SG was created but not used.
2. used your name(ttn-eks-managed-vasu)
3. No description is mentioned in the PR
4. By PR heading it means there is a change in the module but in the changed file, you have added an example, nothing is related to the module issues.

2023-07-09 12:50 UTC, guptavasu1 commented on main.tf
resolve_conflicts was deprecated hence updated

2023-07-09 12:51 UTC, guptavasu1 commented on modules/eks-managed-node-group/main.tf
Reached max character limit hence shorten the name.

2023-07-09 12:53 UTC, guptavasu1 commented on node_groups.tf
Allowing all traffic from the master to node by adding a rule in node SG

2023-07-14 11:01 UTC, merged